# Generated by Django 5.2.11 on 2026-02-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact_info',
        ),
    ]
