# Generated by Django 5.2.11 on 2026-03-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_item_location_alter_item_title_claimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
