# Generated by Django 5.2.11 on 2026-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_claimrequest_status_alter_claimrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('claimed', 'Claimed')], default='pending', max_length=10),
        ),
    ]
